name: nur_ai
description: "Kalbinin Dijital Rehberi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0  # 👈 Bunu ekle
  # --- 1. GÖRSEL & TASARIM ---
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.10
  phosphor_flutter: ^2.1.0

  # --- 2. YAPAY ZEKA ---
  google_generative_ai: ^0.4.0

  # --- 3. SATIN ALMA (PREMIUM) ---
  # 👇 Firebase yerine bunu kullanacağız. Dünyanın en iyisi.
  # 👇 En güncel ve hatasız sürüm
  purchases_flutter: ^8.0.0 

  # --- 4. ARAÇLAR & DEPOLAMA ---
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2 
  url_launcher: ^6.2.4
  screenshot: ^2.1.0  # Widget'ı resme çevirir
  path_provider: ^2.1.0  # Geçici dosya yolu için
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.0
  package_info_plus: ^8.0.0

  # --- 5. İSLAMİ & KONUM ---
  jhijri: ^1.0.0
  intl: ^0.20.2
  adhan: ^2.0.0+1
  geolocator: ^14.0.2
  timezone: ^0.9.4
  flutter_timezone: ^5.0.1
  flutter_compass: ^0.8.0
  # --- 6. BİLDİRİM & REKLAM ---
  flutter_local_notifications: ^17.2.2 
  google_mobile_ads: ^5.1.0
  ntp: ^2.0.0
  quran: ^1.3.1
  geocoding: ^2.1.0
  permission_handler: ^11.3.0
  http: ^1.6.0
  easy_localization: ^3.0.8
  disable_battery_optimization: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # ÖZELLEŞTİRME
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/quran/surah/  
    - assets/translations/

# --- AYARLAR ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#0F172A"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#0F172A"
  fullscreen: true